# Generated by Django 4.0.5 on 2022-07-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go',
            name='age',
            field=models.IntegerField(),
        ),
    ]
