# Generated by Django 4.0.5 on 2022-07-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_department_employee_role_delete_go_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
    ]
